# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build-artifacts:
    name: "Build Artifacts"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../friendly-tournament
    steps:
      - uses: actions/checkout@v3
      - name: npm install and build the friendly-tournament website
        run: |
          npm install --legacy-peer-deps
          npm run build --production
      - uses: actions/upload-artifact@v3
        with:
          name: friendly-tournament
          path: './dist/apps/friendly-tournament'

  run-tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - uses: actions/checkout@v3
      - name: npm install and run test
        run: |
          npm install --legacy-peer-deps
          npm run test

  deploy-to-netlify:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: friendly-tournament
          path: './dist/apps/friendly-tournament'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: './dist/apps/friendly-tournament'
          production-branch: main
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1