# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./friendly-tournament
    steps:
      - uses: actions/checkout@v3
      - name: npm install and build
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: friendly-tournament
          path: './dist/apps/friendly-tournament'

  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./friendly-tournament
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: npm install and run test
        run: |
          npm install
          npm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./friendly-tournament
    needs: |
      test
      build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: friendly-tournament
          path: './dist/apps/friendly-tournament'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        
        with:
          publish-dir: './dist/apps/friendly-tournament'
          production-branch: main
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

    needs: run-tests
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Triplo
          path: './dist/apps/triplo'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.4
        with:
          publish-dir: './dist/apps/triplo'
          production-branch: main
          enable-commit-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1